ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 10

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "wanderer"
file = "images/wanderer.png"
startx = 1979
starty = 829
priority = 2

[[structure]]
name = "wave"
file = "images/wave-banner.png"
startx = 1921
starty = 770
priority = 3

[[structure]]
name = "kobowave"
file = "images/kobowave.png"
startx = 1892
starty = 697
priority = 3

#[[structure]]
#name = "mona"
#file = "images/mona.png"
#startx = 1490
#starty = 1290
#priority = 2