ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 6

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "wanderer"
file = "images/wanderer.png"
startx = 1979
starty = 831
priority = 2

[[structure]]
name = "wave"
file = "images/wave.png"
startx = 1921
starty = 776
priority = 3